name: Discord Bot

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py

      - name: Run bot
        run: python main.py
        
