name: Python Script Workflow
on:
  push:
    branches:
      - main
jobs:
  run-python-script:
    runs-on: windows-latest
    name: Run Python Script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependenciess
        run: pip install -r requirements.txt
      
      - name: Run Python Script
        run: python main.py
